version: '3.8'

services:
  node1:
    build: .
    command: ["-http_port=8000", "-id=1", "-raft_port=5051", "node2:5052", "node3:5053"]
    ports:
      - "8000:8000"
    networks:
      - raft_network

  node2:
    build: .
    command: ["-http_port=8001", "-id=2", "-raft_port=5052", "node1:5051", "node3:5053"]
    ports:
      - "8001:8001"
    networks:
      - raft_network

  node3:
    build: .
    command: ["-http_port=8002", "-id=3", "-raft_port=5053", "node1:5051", "node2:5052"]
    ports:
      - "8002:8002"
    networks:
      - raft_network

networks:
  raft_network:
